#lang racket/base

(require rosette
         "generated/lattice-ecp5-alu54b.rkt"
         "signal.rkt"
         rackunit)

(define (helper state a b c CE CFB CIN CLK OP MA MB RST)

  (lattice-ecp5-alu54b
   #:A0 (signal (bit 0 a) state)
   #:A1 (bv->signal (bit 1 a))
   #:A2 (bv->signal (bit 2 a))
   #:A3 (bv->signal (bit 3 a))
   #:A4 (bv->signal (bit 4 a))
   #:A5 (bv->signal (bit 5 a))
   #:A6 (bv->signal (bit 6 a))
   #:A7 (bv->signal (bit 7 a))
   #:A8 (bv->signal (bit 8 a))
   #:A9 (bv->signal (bit 9 a))
   #:A10 (bv->signal (bit 10 a))
   #:A11 (bv->signal (bit 11 a))
   #:A12 (bv->signal (bit 12 a))
   #:A13 (bv->signal (bit 13 a))
   #:A14 (bv->signal (bit 14 a))
   #:A15 (bv->signal (bit 15 a))
   #:A16 (bv->signal (bit 16 a))
   #:A17 (bv->signal (bit 17 a))
   #:A18 (bv->signal (bit 18 a))
   #:A19 (bv->signal (bit 19 a))
   #:A20 (bv->signal (bit 20 a))
   #:A21 (bv->signal (bit 21 a))
   #:A22 (bv->signal (bit 22 a))
   #:A23 (bv->signal (bit 23 a))
   #:A24 (bv->signal (bit 24 a))
   #:A25 (bv->signal (bit 25 a))
   #:A26 (bv->signal (bit 26 a))
   #:A27 (bv->signal (bit 27 a))
   #:A28 (bv->signal (bit 28 a))
   #:A29 (bv->signal (bit 29 a))
   #:A30 (bv->signal (bit 30 a))
   #:A31 (bv->signal (bit 31 a))
   #:A32 (bv->signal (bit 32 a))
   #:A33 (bv->signal (bit 33 a))
   #:A34 (bv->signal (bit 34 a))
   #:A35 (bv->signal (bit 35 a))
   #:B0 (bv->signal (bit 0 b))
   #:B1 (bv->signal (bit 1 b))
   #:B2 (bv->signal (bit 2 b))
   #:B3 (bv->signal (bit 3 b))
   #:B4 (bv->signal (bit 4 b))
   #:B5 (bv->signal (bit 5 b))
   #:B6 (bv->signal (bit 6 b))
   #:B7 (bv->signal (bit 7 b))
   #:B8 (bv->signal (bit 8 b))
   #:B9 (bv->signal (bit 9 b))
   #:B10 (bv->signal (bit 10 b))
   #:B11 (bv->signal (bit 11 b))
   #:B12 (bv->signal (bit 12 b))
   #:B13 (bv->signal (bit 13 b))
   #:B14 (bv->signal (bit 14 b))
   #:B15 (bv->signal (bit 15 b))
   #:B16 (bv->signal (bit 16 b))
   #:B17 (bv->signal (bit 17 b))
   #:B18 (bv->signal (bit 18 b))
   #:B19 (bv->signal (bit 19 b))
   #:B20 (bv->signal (bit 20 b))
   #:B21 (bv->signal (bit 21 b))
   #:B22 (bv->signal (bit 22 b))
   #:B23 (bv->signal (bit 23 b))
   #:B24 (bv->signal (bit 24 b))
   #:B25 (bv->signal (bit 25 b))
   #:B26 (bv->signal (bit 26 b))
   #:B27 (bv->signal (bit 27 b))
   #:B28 (bv->signal (bit 28 b))
   #:B29 (bv->signal (bit 29 b))
   #:B30 (bv->signal (bit 30 b))
   #:B31 (bv->signal (bit 31 b))
   #:B32 (bv->signal (bit 32 b))
   #:B33 (bv->signal (bit 33 b))
   #:B34 (bv->signal (bit 34 b))
   #:B35 (bv->signal (bit 35 b))
   #:C0 (bv->signal (bit 0 c))
   #:C1 (bv->signal (bit 1 c))
   #:C2 (bv->signal (bit 2 c))
   #:C3 (bv->signal (bit 3 c))
   #:C4 (bv->signal (bit 4 c))
   #:C5 (bv->signal (bit 5 c))
   #:C6 (bv->signal (bit 6 c))
   #:C7 (bv->signal (bit 7 c))
   #:C8 (bv->signal (bit 8 c))
   #:C9 (bv->signal (bit 9 c))
   #:C10 (bv->signal (bit 10 c))
   #:C11 (bv->signal (bit 11 c))
   #:C12 (bv->signal (bit 12 c))
   #:C13 (bv->signal (bit 13 c))
   #:C14 (bv->signal (bit 14 c))
   #:C15 (bv->signal (bit 15 c))
   #:C16 (bv->signal (bit 16 c))
   #:C17 (bv->signal (bit 17 c))
   #:C18 (bv->signal (bit 18 c))
   #:C19 (bv->signal (bit 19 c))
   #:C20 (bv->signal (bit 20 c))
   #:C21 (bv->signal (bit 21 c))
   #:C22 (bv->signal (bit 22 c))
   #:C23 (bv->signal (bit 23 c))
   #:C24 (bv->signal (bit 24 c))
   #:C25 (bv->signal (bit 25 c))
   #:C26 (bv->signal (bit 26 c))
   #:C27 (bv->signal (bit 27 c))
   #:C28 (bv->signal (bit 28 c))
   #:C29 (bv->signal (bit 29 c))
   #:C30 (bv->signal (bit 30 c))
   #:C31 (bv->signal (bit 31 c))
   #:C32 (bv->signal (bit 32 c))
   #:C33 (bv->signal (bit 33 c))
   #:C34 (bv->signal (bit 34 c))
   #:C35 (bv->signal (bit 35 c))
   #:C36 (bv->signal (bit 36 c))
   #:C37 (bv->signal (bit 37 c))
   #:C38 (bv->signal (bit 38 c))
   #:C39 (bv->signal (bit 39 c))
   #:C40 (bv->signal (bit 40 c))
   #:C41 (bv->signal (bit 41 c))
   #:C42 (bv->signal (bit 42 c))
   #:C43 (bv->signal (bit 43 c))
   #:C44 (bv->signal (bit 44 c))
   #:C45 (bv->signal (bit 45 c))
   #:C46 (bv->signal (bit 46 c))
   #:C47 (bv->signal (bit 47 c))
   #:C48 (bv->signal (bit 48 c))
   #:C49 (bv->signal (bit 49 c))
   #:C50 (bv->signal (bit 50 c))
   #:C51 (bv->signal (bit 51 c))
   #:C52 (bv->signal (bit 52 c))
   #:C53 (bv->signal (bit 53 c))
   #:CE0 (bv->signal (bit 0 CE))
   #:CE1 (bv->signal (bit 1 CE))
   #:CE2 (bv->signal (bit 2 CE))
   #:CE3 (bv->signal (bit 3 CE))
   #:CFB0 (bv->signal (bit 0 CFB))
   #:CFB1 (bv->signal (bit 1 CFB))
   #:CFB2 (bv->signal (bit 2 CFB))
   #:CFB3 (bv->signal (bit 3 CFB))
   #:CFB4 (bv->signal (bit 4 CFB))
   #:CFB5 (bv->signal (bit 5 CFB))
   #:CFB6 (bv->signal (bit 6 CFB))
   #:CFB7 (bv->signal (bit 7 CFB))
   #:CFB8 (bv->signal (bit 8 CFB))
   #:CFB9 (bv->signal (bit 9 CFB))
   #:CFB10 (bv->signal (bit 10 CFB))
   #:CFB11 (bv->signal (bit 11 CFB))
   #:CFB12 (bv->signal (bit 12 CFB))
   #:CFB13 (bv->signal (bit 13 CFB))
   #:CFB14 (bv->signal (bit 14 CFB))
   #:CFB15 (bv->signal (bit 15 CFB))
   #:CFB16 (bv->signal (bit 16 CFB))
   #:CFB17 (bv->signal (bit 17 CFB))
   #:CFB18 (bv->signal (bit 18 CFB))
   #:CFB19 (bv->signal (bit 19 CFB))
   #:CFB20 (bv->signal (bit 20 CFB))
   #:CFB21 (bv->signal (bit 21 CFB))
   #:CFB22 (bv->signal (bit 22 CFB))
   #:CFB23 (bv->signal (bit 23 CFB))
   #:CFB24 (bv->signal (bit 24 CFB))
   #:CFB25 (bv->signal (bit 25 CFB))
   #:CFB26 (bv->signal (bit 26 CFB))
   #:CFB27 (bv->signal (bit 27 CFB))
   #:CFB28 (bv->signal (bit 28 CFB))
   #:CFB29 (bv->signal (bit 29 CFB))
   #:CFB30 (bv->signal (bit 30 CFB))
   #:CFB31 (bv->signal (bit 31 CFB))
   #:CFB32 (bv->signal (bit 32 CFB))
   #:CFB33 (bv->signal (bit 33 CFB))
   #:CFB34 (bv->signal (bit 34 CFB))
   #:CFB35 (bv->signal (bit 35 CFB))
   #:CFB36 (bv->signal (bit 36 CFB))
   #:CFB37 (bv->signal (bit 37 CFB))
   #:CFB38 (bv->signal (bit 38 CFB))
   #:CFB39 (bv->signal (bit 39 CFB))
   #:CFB40 (bv->signal (bit 40 CFB))
   #:CFB41 (bv->signal (bit 41 CFB))
   #:CFB42 (bv->signal (bit 42 CFB))
   #:CFB43 (bv->signal (bit 43 CFB))
   #:CFB44 (bv->signal (bit 44 CFB))
   #:CFB45 (bv->signal (bit 45 CFB))
   #:CFB46 (bv->signal (bit 46 CFB))
   #:CFB47 (bv->signal (bit 47 CFB))
   #:CFB48 (bv->signal (bit 48 CFB))
   #:CFB49 (bv->signal (bit 49 CFB))
   #:CFB50 (bv->signal (bit 50 CFB))
   #:CFB51 (bv->signal (bit 51 CFB))
   #:CFB52 (bv->signal (bit 52 CFB))
   #:CFB53 (bv->signal (bit 53 CFB))
   #:CIN0 (bv->signal (bit 0 CIN))
   #:CIN1 (bv->signal (bit 1 CIN))
   #:CIN2 (bv->signal (bit 2 CIN))
   #:CIN3 (bv->signal (bit 3 CIN))
   #:CIN4 (bv->signal (bit 4 CIN))
   #:CIN5 (bv->signal (bit 5 CIN))
   #:CIN6 (bv->signal (bit 6 CIN))
   #:CIN7 (bv->signal (bit 7 CIN))
   #:CIN8 (bv->signal (bit 8 CIN))
   #:CIN9 (bv->signal (bit 9 CIN))
   #:CIN10 (bv->signal (bit 10 CIN))
   #:CIN11 (bv->signal (bit 11 CIN))
   #:CIN12 (bv->signal (bit 12 CIN))
   #:CIN13 (bv->signal (bit 13 CIN))
   #:CIN14 (bv->signal (bit 14 CIN))
   #:CIN15 (bv->signal (bit 15 CIN))
   #:CIN16 (bv->signal (bit 16 CIN))
   #:CIN17 (bv->signal (bit 17 CIN))
   #:CIN18 (bv->signal (bit 18 CIN))
   #:CIN19 (bv->signal (bit 19 CIN))
   #:CIN20 (bv->signal (bit 20 CIN))
   #:CIN21 (bv->signal (bit 21 CIN))
   #:CIN22 (bv->signal (bit 22 CIN))
   #:CIN23 (bv->signal (bit 23 CIN))
   #:CIN24 (bv->signal (bit 24 CIN))
   #:CIN25 (bv->signal (bit 25 CIN))
   #:CIN26 (bv->signal (bit 26 CIN))
   #:CIN27 (bv->signal (bit 27 CIN))
   #:CIN28 (bv->signal (bit 28 CIN))
   #:CIN29 (bv->signal (bit 29 CIN))
   #:CIN30 (bv->signal (bit 30 CIN))
   #:CIN31 (bv->signal (bit 31 CIN))
   #:CIN32 (bv->signal (bit 32 CIN))
   #:CIN33 (bv->signal (bit 33 CIN))
   #:CIN34 (bv->signal (bit 34 CIN))
   #:CIN35 (bv->signal (bit 35 CIN))
   #:CIN36 (bv->signal (bit 36 CIN))
   #:CIN37 (bv->signal (bit 37 CIN))
   #:CIN38 (bv->signal (bit 38 CIN))
   #:CIN39 (bv->signal (bit 39 CIN))
   #:CIN40 (bv->signal (bit 40 CIN))
   #:CIN41 (bv->signal (bit 41 CIN))
   #:CIN42 (bv->signal (bit 42 CIN))
   #:CIN43 (bv->signal (bit 43 CIN))
   #:CIN44 (bv->signal (bit 44 CIN))
   #:CIN45 (bv->signal (bit 45 CIN))
   #:CIN46 (bv->signal (bit 46 CIN))
   #:CIN47 (bv->signal (bit 47 CIN))
   #:CIN48 (bv->signal (bit 48 CIN))
   #:CIN49 (bv->signal (bit 49 CIN))
   #:CIN50 (bv->signal (bit 50 CIN))
   #:CIN51 (bv->signal (bit 51 CIN))
   #:CIN52 (bv->signal (bit 52 CIN))
   #:CIN53 (bv->signal (bit 53 CIN))
   #:CLK0 (bv->signal (bit 0 CLK))
   #:CLK1 (bv->signal (bit 1 CLK))
   #:CLK2 (bv->signal (bit 2 CLK))
   #:CLK3 (bv->signal (bit 3 CLK))
   #:FORCE_ZERO_BARREL_SHIFT (bv->signal (constant 'FORCE_ZERO_BARREL_SHIFT (bitvector 5)))
   #:LEGACY (bv->signal (constant 'LEGACY (bitvector 5)))
   #:MA0 (bv->signal (bit 0 MA))
   #:MA1 (bv->signal (bit 1 MA))
   #:MA2 (bv->signal (bit 2 MA))
   #:MA3 (bv->signal (bit 3 MA))
   #:MA4 (bv->signal (bit 4 MA))
   #:MA5 (bv->signal (bit 5 MA))
   #:MA6 (bv->signal (bit 6 MA))
   #:MA7 (bv->signal (bit 7 MA))
   #:MA8 (bv->signal (bit 8 MA))
   #:MA9 (bv->signal (bit 9 MA))
   #:MA10 (bv->signal (bit 10 MA))
   #:MA11 (bv->signal (bit 11 MA))
   #:MA12 (bv->signal (bit 12 MA))
   #:MA13 (bv->signal (bit 13 MA))
   #:MA14 (bv->signal (bit 14 MA))
   #:MA15 (bv->signal (bit 15 MA))
   #:MA16 (bv->signal (bit 16 MA))
   #:MA17 (bv->signal (bit 17 MA))
   #:MA18 (bv->signal (bit 18 MA))
   #:MA19 (bv->signal (bit 19 MA))
   #:MA20 (bv->signal (bit 20 MA))
   #:MA21 (bv->signal (bit 21 MA))
   #:MA22 (bv->signal (bit 22 MA))
   #:MA23 (bv->signal (bit 23 MA))
   #:MA24 (bv->signal (bit 24 MA))
   #:MA25 (bv->signal (bit 25 MA))
   #:MA26 (bv->signal (bit 26 MA))
   #:MA27 (bv->signal (bit 27 MA))
   #:MA28 (bv->signal (bit 28 MA))
   #:MA29 (bv->signal (bit 29 MA))
   #:MA30 (bv->signal (bit 30 MA))
   #:MA31 (bv->signal (bit 31 MA))
   #:MA32 (bv->signal (bit 32 MA))
   #:MA33 (bv->signal (bit 33 MA))
   #:MA34 (bv->signal (bit 34 MA))
   #:MA35 (bv->signal (bit 35 MA))
   #:MASK01 (bv->signal (constant 'MASK01 (bitvector 56)))
   #:MASKPAT (bv->signal (constant 'MASKPAT (bitvector 56)))
   #:MASKPAT_SOURCE (bv->signal (constant 'MASKPAT_SOURCE (bitvector 5)))
   #:MB0 (bv->signal (bit 0 MB))
   #:MB1 (bv->signal (bit 1 MB))
   #:MB2 (bv->signal (bit 2 MB))
   #:MB3 (bv->signal (bit 3 MB))
   #:MB4 (bv->signal (bit 4 MB))
   #:MB5 (bv->signal (bit 5 MB))
   #:MB6 (bv->signal (bit 6 MB))
   #:MB7 (bv->signal (bit 7 MB))
   #:MB8 (bv->signal (bit 8 MB))
   #:MB9 (bv->signal (bit 9 MB))
   #:MB10 (bv->signal (bit 10 MB))
   #:MB11 (bv->signal (bit 11 MB))
   #:MB12 (bv->signal (bit 12 MB))
   #:MB13 (bv->signal (bit 13 MB))
   #:MB14 (bv->signal (bit 14 MB))
   #:MB15 (bv->signal (bit 15 MB))
   #:MB16 (bv->signal (bit 16 MB))
   #:MB17 (bv->signal (bit 17 MB))
   #:MB18 (bv->signal (bit 18 MB))
   #:MB19 (bv->signal (bit 19 MB))
   #:MB20 (bv->signal (bit 20 MB))
   #:MB21 (bv->signal (bit 21 MB))
   #:MB22 (bv->signal (bit 22 MB))
   #:MB23 (bv->signal (bit 23 MB))
   #:MB24 (bv->signal (bit 24 MB))
   #:MB25 (bv->signal (bit 25 MB))
   #:MB26 (bv->signal (bit 26 MB))
   #:MB27 (bv->signal (bit 27 MB))
   #:MB28 (bv->signal (bit 28 MB))
   #:MB29 (bv->signal (bit 29 MB))
   #:MB30 (bv->signal (bit 30 MB))
   #:MB31 (bv->signal (bit 31 MB))
   #:MB32 (bv->signal (bit 32 MB))
   #:MB33 (bv->signal (bit 33 MB))
   #:MB34 (bv->signal (bit 34 MB))
   #:MB35 (bv->signal (bit 35 MB))
   #:MCPAT (bv->signal (constant 'MCPAT (bitvector 56)))
   #:MCPAT_SOURCE (bv->signal (constant 'MCPAT_SOURCE (bitvector 5)))
   #:MULT9_MODE (bv->signal (constant 'MULT9_MODE (bitvector 5)))
   #:OP0 (bv->signal (bit 0 OP))
   #:OP1 (bv->signal (bit 1 OP))
   #:OP2 (bv->signal (bit 2 OP))
   #:OP3 (bv->signal (bit 3 OP))
   #:OP4 (bv->signal (bit 4 OP))
   #:OP5 (bv->signal (bit 5 OP))
   #:OP6 (bv->signal (bit 6 OP))
   #:OP7 (bv->signal (bit 7 OP))
   #:OP8 (bv->signal (bit 8 OP))
   #:OP9 (bv->signal (bit 9 OP))
   #:OP10 (bv->signal (bit 10 OP))
   #:REG_INPUTCFB_CE (bv->signal (constant 'REG_INPUTCFB_CE (bitvector 5)))
   #:REG_INPUTCFB_CLK (bv->signal (constant 'REG_INPUTCFB_CLK (bitvector 5)))
   #:REG_INPUTCFB_RST (bv->signal (constant 'REG_INPUTCFB_RST (bitvector 5)))
   #:RNDPAT (bv->signal (constant 'RNDPAT (bitvector 56)))
   #:RST0 (bv->signal (bit 0 RST))
   #:RST1 (bv->signal (bit 1 RST))
   #:RST2 (bv->signal (bit 2 RST))
   #:RST3 (bv->signal (bit 3 RST))
   #:SIGNEDCIN (bv->signal (constant 'SIGNEDCIN (bitvector 1)))
   #:SIGNEDIA (bv->signal (constant 'SIGNEDIA (bitvector 1)))
   #:SIGNEDIB (bv->signal (constant 'SIGNEDIB (bitvector 1)))
   #:unnamed-input-872 (bv->signal (constant 'unnamed-input-872 (bitvector 55)))
   #:unnamed-input-1118 (bv->signal (constant 'unnamed-input-1118 (bitvector 55)))
   #:unnamed-input-1364 (bv->signal (constant 'unnamed-input-1364 (bitvector 55)))))

(define-symbolic a-input b-input (bitvector 36))
(define-symbolic c-input (bitvector 54))
(define-symbolic opcode (bitvector 11))

(define o0
  (helper '()
          ;;; A
          (bv 0 36)
          ;;; B
          (bv 0 36)
          ;;; C
          c-input
          ;;; CE
          (bv #b1111 4)
          ;;; CFB
          (bv 0 54)
          ;;; CIN
          (bv 0 54)
          ;;; CLK
          (bv #b0000 4)
          ;;; OP
          opcode
          ;;; MA
          a-input
          ;;; MB
          b-input
          ;;; RST
          (bv #b0000 4)))

(define o1
  (helper (signal-state (cdr (assoc 'R0 o0)))
          ;;; A
          (bv 0 36)
          ;;; B
          (bv 0 36)
          ;;; C
          c-input
          ;;; CE
          (bv #b1111 4)
          ;;; CFB
          (bv 0 54)
          ;;; CIN
          (bv 0 54)
          ;;; CLK
          (bv #b1111 4)
          ;;; OP
          opcode
          ;;; MA
          a-input
          ;;; MB
          b-input
          ;;; RST
          (bv #b0000 4)))

(define o2
  (helper (signal-state (cdr (assoc 'R0 o1)))
          ;;; A
          (bv 0 36)
          ;;; B
          (bv 0 36)
          ;;; C
          c-input
          ;;; CE
          (bv #b1111 4)
          ;;; CFB
          (bv 0 54)
          ;;; CIN
          (bv 0 54)
          ;;; CLK
          (bv #b0000 4)
          ;;; OP
          opcode
          ;;; MA
          a-input
          ;;; MB
          b-input
          ;;; RST
          (bv #b0000 4)))

(define o3
  (helper (signal-state (cdr (assoc 'R0 o2)))
          ;;; A
          (bv 0 36)
          ;;; B
          (bv 0 36)
          ;;; C
          c-input
          ;;; CE
          (bv #b1111 4)
          ;;; CFB
          (bv 0 54)
          ;;; CIN
          (bv 0 54)
          ;;; CLK
          (bv #b1111 4)
          ;;; OP
          opcode
          ;;; MA
          a-input
          ;;; MB
          b-input
          ;;; RST
          (bv #b0000 4)))

(test-true "synthesize a + b"
           (sat? (synthesize #:forall (list a-input b-input)
                             #:guarantee
                             (assert (bveq (concat (signal-value (assoc-ref o3 'R53))
                                                   (signal-value (assoc-ref o3 'R52))
                                                   (signal-value (assoc-ref o3 'R51))
                                                   (signal-value (assoc-ref o3 'R50))
                                                   (signal-value (assoc-ref o3 'R49))
                                                   (signal-value (assoc-ref o3 'R48))
                                                   (signal-value (assoc-ref o3 'R47))
                                                   (signal-value (assoc-ref o3 'R46))
                                                   (signal-value (assoc-ref o3 'R45))
                                                   (signal-value (assoc-ref o3 'R44))
                                                   (signal-value (assoc-ref o3 'R43))
                                                   (signal-value (assoc-ref o3 'R42))
                                                   (signal-value (assoc-ref o3 'R41))
                                                   (signal-value (assoc-ref o3 'R40))
                                                   (signal-value (assoc-ref o3 'R39))
                                                   (signal-value (assoc-ref o3 'R38))
                                                   (signal-value (assoc-ref o3 'R37))
                                                   (signal-value (assoc-ref o3 'R36))
                                                   (signal-value (assoc-ref o3 'R35))
                                                   (signal-value (assoc-ref o3 'R34))
                                                   (signal-value (assoc-ref o3 'R33))
                                                   (signal-value (assoc-ref o3 'R32))
                                                   (signal-value (assoc-ref o3 'R31))
                                                   (signal-value (assoc-ref o3 'R30))
                                                   (signal-value (assoc-ref o3 'R29))
                                                   (signal-value (assoc-ref o3 'R28))
                                                   (signal-value (assoc-ref o3 'R27))
                                                   (signal-value (assoc-ref o3 'R26))
                                                   (signal-value (assoc-ref o3 'R25))
                                                   (signal-value (assoc-ref o3 'R24))
                                                   (signal-value (assoc-ref o3 'R23))
                                                   (signal-value (assoc-ref o3 'R22))
                                                   (signal-value (assoc-ref o3 'R21))
                                                   (signal-value (assoc-ref o3 'R20))
                                                   (signal-value (assoc-ref o3 'R19))
                                                   (signal-value (assoc-ref o3 'R18))
                                                   (signal-value (assoc-ref o3 'R17))
                                                   (signal-value (assoc-ref o3 'R16))
                                                   (signal-value (assoc-ref o3 'R15))
                                                   (signal-value (assoc-ref o3 'R14))
                                                   (signal-value (assoc-ref o3 'R13))
                                                   (signal-value (assoc-ref o3 'R12))
                                                   (signal-value (assoc-ref o3 'R11))
                                                   (signal-value (assoc-ref o3 'R10))
                                                   (signal-value (assoc-ref o3 'R9))
                                                   (signal-value (assoc-ref o3 'R8))
                                                   (signal-value (assoc-ref o3 'R7))
                                                   (signal-value (assoc-ref o3 'R6))
                                                   (signal-value (assoc-ref o3 'R5))
                                                   (signal-value (assoc-ref o3 'R4))
                                                   (signal-value (assoc-ref o3 'R3))
                                                   (signal-value (assoc-ref o3 'R2))
                                                   (signal-value (assoc-ref o3 'R1))
                                                   (signal-value (assoc-ref o3 'R0)))
                                           (bvadd (zero-extend a-input (bitvector 54))
                                                  (zero-extend b-input (bitvector 54))))))))

(test-true "synthesize a + b + c"
           (sat? (synthesize #:forall (list a-input b-input c-input)
                             #:guarantee
                             (assert (bveq (concat (signal-value (assoc-ref o3 'R53))
                                                   (signal-value (assoc-ref o3 'R52))
                                                   (signal-value (assoc-ref o3 'R51))
                                                   (signal-value (assoc-ref o3 'R50))
                                                   (signal-value (assoc-ref o3 'R49))
                                                   (signal-value (assoc-ref o3 'R48))
                                                   (signal-value (assoc-ref o3 'R47))
                                                   (signal-value (assoc-ref o3 'R46))
                                                   (signal-value (assoc-ref o3 'R45))
                                                   (signal-value (assoc-ref o3 'R44))
                                                   (signal-value (assoc-ref o3 'R43))
                                                   (signal-value (assoc-ref o3 'R42))
                                                   (signal-value (assoc-ref o3 'R41))
                                                   (signal-value (assoc-ref o3 'R40))
                                                   (signal-value (assoc-ref o3 'R39))
                                                   (signal-value (assoc-ref o3 'R38))
                                                   (signal-value (assoc-ref o3 'R37))
                                                   (signal-value (assoc-ref o3 'R36))
                                                   (signal-value (assoc-ref o3 'R35))
                                                   (signal-value (assoc-ref o3 'R34))
                                                   (signal-value (assoc-ref o3 'R33))
                                                   (signal-value (assoc-ref o3 'R32))
                                                   (signal-value (assoc-ref o3 'R31))
                                                   (signal-value (assoc-ref o3 'R30))
                                                   (signal-value (assoc-ref o3 'R29))
                                                   (signal-value (assoc-ref o3 'R28))
                                                   (signal-value (assoc-ref o3 'R27))
                                                   (signal-value (assoc-ref o3 'R26))
                                                   (signal-value (assoc-ref o3 'R25))
                                                   (signal-value (assoc-ref o3 'R24))
                                                   (signal-value (assoc-ref o3 'R23))
                                                   (signal-value (assoc-ref o3 'R22))
                                                   (signal-value (assoc-ref o3 'R21))
                                                   (signal-value (assoc-ref o3 'R20))
                                                   (signal-value (assoc-ref o3 'R19))
                                                   (signal-value (assoc-ref o3 'R18))
                                                   (signal-value (assoc-ref o3 'R17))
                                                   (signal-value (assoc-ref o3 'R16))
                                                   (signal-value (assoc-ref o3 'R15))
                                                   (signal-value (assoc-ref o3 'R14))
                                                   (signal-value (assoc-ref o3 'R13))
                                                   (signal-value (assoc-ref o3 'R12))
                                                   (signal-value (assoc-ref o3 'R11))
                                                   (signal-value (assoc-ref o3 'R10))
                                                   (signal-value (assoc-ref o3 'R9))
                                                   (signal-value (assoc-ref o3 'R8))
                                                   (signal-value (assoc-ref o3 'R7))
                                                   (signal-value (assoc-ref o3 'R6))
                                                   (signal-value (assoc-ref o3 'R5))
                                                   (signal-value (assoc-ref o3 'R4))
                                                   (signal-value (assoc-ref o3 'R3))
                                                   (signal-value (assoc-ref o3 'R2))
                                                   (signal-value (assoc-ref o3 'R1))
                                                   (signal-value (assoc-ref o3 'R0)))
                                           (bvadd (bvadd (zero-extend a-input (bitvector 54))
                                                         (zero-extend b-input (bitvector 54)))
                                                  c-input))))))
