# Taken from Herbie:
# https://github.com/herbie-fp/herbie/blob/400891fe4c89f0cee051b8e03089a01ab9016f4b/.github/workflows/release.yml
name: Generate Lakeroad release

on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:
  # DO NOT MERGE: we are just including this so that we can test the release
  # while working on the PR.
  pull_request:

jobs:
  build:
    name: Build
    strategy:
      # manual matrix: I think this was an easy way to make (os, os-name) pairs.
      matrix:
        include:
          - os: windows-latest
            os-name: windows
          - os: ubuntu-latest
            os-name: ubuntu
          - os: macos-latest
            os-name: macOS

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.11
        with:
          version: 8.11

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: raco exe
        run: raco exe -o lakeroad-single-solver bin/main.rkt


      - name: Zip everything
        run: |
          zip -r lakeroad-${{ matrix.os-name }}.zip lakeroad-single-solver
          sha256sum lakeroad-${{ matrix.os-name }}.zip > lakeroad-${{ matrix.os-name }}.zip.CHECKSUM

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: lakeroad-${{ matrix.os-name }}.zip
          name: lakeroad-${{ matrix.os-name }}.zip
          if-no-files-found: error

      - name: Upload pre-built egg-herbie checksum
        uses: actions/upload-artifact@v4
        with:
          path: lakeroad-${{ matrix.os-name }}.zip.CHECKSUM
          name: lakeroad-${{ matrix.os-name }}.zip.CHECKSUM
          if-no-files-found: error

  release:
    name: Create Initial Release
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download pre-built artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: lakeroad-*
          merge-multiple: true

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: ${{ github.ref }}
          commit: ${{ github.commit }}
          draft: true
          prerelease: false
          artifactErrorsFailBuild: true
          artifacts: "artifacts/*"
